image: docker:latest
services:
  - docker:dind

stages:
  - build
  # - deploy

build:
  stage: build
  script:
    - docker build -f ./config/client.prod.Dockerfile -t registry.gitlab.com/pburris/cursors/client .
    - docker build -f ./config/server.Dockerfile -t registry.gitlab.com/pburris/cursors/server .
    - docker tag registry.gitlab.com/pburris/cursors/client registry.gitlab.com/pburris/cursors/client:latest
    - docker tag registry.gitlab.com/pburris/cursors/server registry.gitlab.com/pburris/cursors/server:latest
    - docker push registry.gitlab.com/pburris/cursors/client:latest
    - docker push registry.gitlab.com/pburris/cursors/server:latest

# deploy:
#   stage: deploy
#   image: dtzar/helm-kubectl
#   script:
#     # - kubectl config set-cluster k8s --server="${SERVER}"
#     # - kubectl config set clusters.k8s.certificate-authority-data ${CERTIFICATE_AUTHORITY_DATA}
#     # - kubectl config set-credentials gitlab --token="${USER_TOKEN}"
#     # - kubectl config set-context default --cluster=k8s --user=gitlab
#     # - kubectl config use-context default
#     # - sed -i "s/<VERSION>/${CI_COMMIT_SHORT_SHA}/g" deployment.yaml
#     # - kubectl apply -f deployment.yaml