image: docker:latest
services:
  - docker:dind

stages:
  # - build
  - deploy

variables:
  REG_BASE_URI: registry.gitlab.com
  REG_BASE: ${REG_BASE_URI}/pburris/cursors
  REG_USER: gitlab-ci-token

  K8S_CLUSTER_URL: 34.72.232.130

# build:
#   stage: build
#   script:
#     - docker login -u ${REG_USER} -p ${REG_TOKEN} ${REG_BASE}
#     - docker build -f ./config/client.prod.Dockerfile -t ${REG_BASE}/client .
#     - docker build -f ./config/server.Dockerfile -t ${REG_BASE}/server .
#     - docker tag ${REG_BASE}/client ${REG_BASE}/client:latest
#     - docker tag ${REG_BASE}/server ${REG_BASE}/server:latest
#     - docker push ${REG_BASE}/client:latest
#     - docker push ${REG_BASE}/server:latest

deploy:
  stage: deploy
  image: dtzar/helm-kubectl
  script:
    - kubectl config set-cluster k8s --server="${K8S_CLUSTER_URL}"
    # - kubectl config set clusters.k8s.certificate-authority-data ${K8S_CERT_AUTH}
    - kubectl config set-credentials gitlab --token="${K8S_TOKEN}"
    - kubectl config set-context default --cluster=k8s --user=gitlab
    - kubectl config use-context default
    - kubectl apply -f ./k8s