image: docker:latest
services:
  - docker:dind

stages:
  - build
  # - deploy

variables:
  REG_BASE_URI: registry.gitlab.com
  REG_BASE: ${REG_BASE_URI}/pburris/cursors

build:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p ${REG_TOKEN} ${REG_BASE}
    - docker build -f ./config/client.prod.Dockerfile -t ${REG_BASE}/client .
    - docker build -f ./config/server.Dockerfile -t ${REG_BASE}/server .
    - docker tag ${REG_BASE}/client ${REG_BASE}/client:latest
    - docker tag ${REG_BASE}/server ${REG_BASE}/server:latest
    - docker push ${REG_BASE}/client:latest
    - docker push ${REG_BASE}/server:latest

# deploy:
#   stage: deploy
#   image: dtzar/helm-kubectl
#   script:
#     # - kubectl config set-cluster k8s --server="${SERVER}"
#     # - kubectl config set clusters.k8s.certificate-authority-data ${CERTIFICATE_AUTHORITY_DATA}
#     # - kubectl config set-credentials gitlab --token="${USER_TOKEN}"
#     # - kubectl config set-context default --cluster=k8s --user=gitlab
#     # - kubectl config use-context default
#     # - sed -i "s/<VERSION>/${CI_COMMIT_SHORT_SHA}/g" deployment.yaml
#     # - kubectl apply -f deployment.yaml