version: '3'

services:

  nginx:
    container_name: nginx
    build:
        context: ./config
        dockerfile: nginx.Dockerfile
    depends_on:
        - api
        - client
    ports:
        - 3050:80
        - 8080:8080

  client:
    container_name: client
    build:
      context: ./
      dockerfile: ./config/client.dev.Dockerfile 
    depends_on:
      - api
    restart: always
    environment:
      NODE_ENV: local
    volumes:
      - ./client:/opt/nodejs/app
      - /opt/nodejs/app/node_modules

  api:
    container_name: api
    build:
      context: ./
      dockerfile: ./config/server.Dockerfile 
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      NODE_PORT: 5000
    restart: always
    command: npm run start:dev
    volumes:
      - ./server:/opt/nodejs/app
      - /opt/nodejs/app/node_modules

  redis:
    container_name: redis
    image: redis
    restart: always